"""empty message

Revision ID: 49f949717c0e
Revises: 8e56121c925f
Create Date: 2018-09-24 16:43:03.252112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49f949717c0e'
down_revision = '8e56121c925f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=200), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
